apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-system

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-sa
  namespace: actions-runner-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner-pod-manager
  namespace: actions-runner-system
rules:
  - apiGroups:
      - ""                
    resources:
      - pods
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ""                 
    resources:
      - pods/log
    verbs:
      - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-pod-manager-binding
  namespace: actions-runner-system
subjects:
  - kind: ServiceAccount
    name: runner-sa
    namespace: actions-runner-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runner-pod-manager

---

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
  namespace: actions-runner-system
spec:
  replicas: ${runner_replicas}
  template:
    spec:
      repository: ${github_repo}
      serviceAccountName: runner-sa
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager
